# Generated by Django 5.1.6 on 2026-09-20 02:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_phone_validator_allows_anonymized'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, verbose_name='الاسم')),
                ('message_template', models.TextField(help_text='يدعم {name} و {balance} و {brand}', verbose_name='نص الرسالة')),
                ('segment_query', models.JSONField(blank=True, default=dict, verbose_name='شريحة المستهدفين')),
                ('channel_priority', models.JSONField(blank=True, default=list, help_text='افتراضيًا: push ← whatsapp ← sms', verbose_name='ترتيب القنوات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدولة'), ('sending', 'قيد الإرسال'), ('sent', 'أُرسلت'), ('cancelled', 'ملغاة'), ('failed', 'فشلت')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='موعد الإرسال')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('estimated_recipients', models.PositiveIntegerField(default=0, verbose_name='عدد المستهدفين المقدَّر')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='التكلفة المقدَّرة')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='التكلفة الفعلية')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenancy.brand', verbose_name='العلامة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='tenancy.staffuser', verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'حملة',
                'verbose_name_plural': 'الحملات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('push', 'إشعار التطبيق'), ('whatsapp', 'واتساب'), ('sms', 'رسالة نصية')], max_length=20, verbose_name='القناة')),
                ('status', models.CharField(choices=[('queued', 'في الطابور'), ('sent', 'أُرسلت'), ('delivered', 'وصلت'), ('read', 'قُرئت'), ('failed', 'فشلت'), ('skipped', 'تُخطّيت')], db_index=True, default='queued', max_length=20, verbose_name='الحالة')),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='التكلفة')),
                ('provider_msg_id', models.CharField(blank=True, max_length=120, verbose_name='مرجع المزوّد')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='سبب الفشل')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإرسال')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='campaigns.campaign', verbose_name='الحملة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_jobs', to='accounts.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['campaign', 'status'], name='job_campaign_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'customer'), name='unique_recipient_per_campaign')],
            },
        ),
    ]
