# Generated by Django 5.1.6 on 2026-09-20 01:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='المعرّف')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='الفئة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='الشعار')),
                ('primary_color', models.CharField(default='#1F6F5C', max_length=7, verbose_name='اللون الأساسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'علامة تجارية',
                'verbose_name_plural': 'العلامات التجارية',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='الاسم')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='الاسم القانوني')),
                ('tax_id', models.CharField(blank=True, max_length=40, verbose_name='الرقم الضريبي')),
                ('billing_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد الفوترة')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('suspended', 'موقوفة')], default='active', max_length=20, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'مؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('opening_hours', models.JSONField(blank=True, null=True, verbose_name='مواعيد العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenancy.brand', verbose_name='العلامة')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ('brand__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='tenancy.organization', verbose_name='المؤسسة'),
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'مالك'), ('manager', 'مدير'), ('cashier', 'كاشير')], default='cashier', max_length=20, verbose_name='الدور')),
                ('pin_hash', models.CharField(blank=True, max_length=128, verbose_name='تجزئة الرمز السري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenancy.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ('branch__name', 'role'),
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=60, verbose_name='التسمية')),
                ('current_code', models.CharField(blank=True, max_length=12, verbose_name='الرمز الحالي')),
                ('code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء الرمز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='tenancy.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'نقطة بيع',
                'verbose_name_plural': 'نقاط البيع',
                'ordering': ('branch__name', 'label'),
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['lat', 'lng'], name='branch_geo_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffuser',
            constraint=models.UniqueConstraint(fields=('user', 'branch'), name='unique_staff_per_branch'),
        ),
    ]
