"""
حقول الدليل العام.

`governorate` رمز من `apps.tenancy.geo` لا نص حر — راجع التعليق
على الحقل في النموذج. الحقل يقبل الفراغ لأن الفروع القائمة قبل
هذه الهجرة لا محافظة لها، و`seed_network` يملؤها للشبكة المتعاقدة.
"""

# Generated by Django 5.1.6 on 2026-09-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="city",
            field=models.CharField(blank=True, max_length=80, verbose_name="المدينة"),
        ),
        migrations.AddField(
            model_name="branch",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAI", "القاهرة"),
                    ("GIZ", "الجيزة"),
                    ("QLY", "القليوبية"),
                    ("ALX", "الإسكندرية"),
                    ("BHR", "البحيرة"),
                    ("KFS", "كفر الشيخ"),
                    ("GHR", "الغربية"),
                    ("MNF", "المنوفية"),
                    ("DKH", "الدقهلية"),
                    ("DMT", "دمياط"),
                    ("SHR", "الشرقية"),
                    ("PTS", "بورسعيد"),
                    ("ISM", "الإسماعيلية"),
                    ("SUZ", "السويس"),
                    ("FYM", "الفيوم"),
                    ("BNS", "بني سويف"),
                    ("MNY", "المنيا"),
                    ("AST", "أسيوط"),
                    ("SHG", "سوهاج"),
                    ("QNA", "قنا"),
                    ("LUX", "الأقصر"),
                    ("ASN", "أسوان"),
                    ("RSS", "البحر الأحمر"),
                    ("WAD", "الوادي الجديد"),
                    ("MAT", "مطروح"),
                    ("NSI", "شمال سيناء"),
                    ("SSI", "جنوب سيناء"),
                ],
                db_index=True,
                max_length=3,
                verbose_name="المحافظة",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="is_listed",
            field=models.BooleanField(
                default=True,
                help_text="إخفاؤها لا يوقف برنامجها — يمنع ظهورها في الخريطة والصفحة العامة فقط.",
                verbose_name="تظهر في الدليل العام",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="joined_on",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ التعاقد"),
        ),
        migrations.AddField(
            model_name="brand",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="سطر واحد يظهر في الدليل العام وبطاقة العميل.",
                max_length=120,
                verbose_name="الوصف المختصر",
            ),
        ),
    ]
