# Generated by Django 5.1.6 on 2026-09-20 01:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('staff', 'موظف'), ('customer', 'عميل'), ('system', 'النظام')], default='system', max_length=20, verbose_name='نوع الفاعل')),
                ('actor_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف الفاعل')),
                ('actor_label', models.CharField(blank=True, max_length=120, verbose_name='اسم الفاعل')),
                ('action', models.CharField(db_index=True, max_length=80, verbose_name='الإجراء')),
                ('entity_type', models.CharField(blank=True, max_length=80, verbose_name='نوع الكيان')),
                ('entity_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف الكيان')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='قبل')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='بعد')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='العنوان')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='المتصفح')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_idx')],
            },
        ),
    ]
