# Generated by Django 5.1.6 on 2026-09-20 02:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('free', 'مجانية'), ('starter', 'أساسية'), ('growth', 'نمو'), ('chain', 'سلاسل')], default='free', max_length=20, verbose_name='الباقة')),
                ('status', models.CharField(choices=[('trial', 'تجريبي'), ('active', 'نشط'), ('past_due', 'متأخر السداد'), ('cancelled', 'ملغى')], default='trial', max_length=20, verbose_name='الحالة')),
                ('mrr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الإيراد الشهري')),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='بداية الدورة')),
                ('current_period_end', models.DateTimeField(db_index=True, verbose_name='نهاية الدورة')),
                ('gateway_ref', models.CharField(blank=True, max_length=120, verbose_name='مرجع البوابة')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenancy.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='الرقم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='القيمة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='الضريبة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('issued', 'صادرة'), ('paid', 'مدفوعة'), ('void', 'ملغاة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('period_start', models.DateTimeField(verbose_name='من')),
                ('period_end', models.DateTimeField(verbose_name='إلى')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ السداد')),
                ('payment_ref', models.CharField(blank=True, max_length=120, verbose_name='مرجع السداد')),
                ('pdf_url', models.URLField(blank=True, verbose_name='ملف PDF')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.subscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MessageCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField(verbose_name='المقدار')),
                ('reason', models.CharField(choices=[('topup', 'شحن'), ('monthly_grant', 'منحة شهرية'), ('send', 'إرسال'), ('refund', 'استرداد'), ('adjust', 'تسوية')], max_length=20, verbose_name='السبب')),
                ('balance_after', models.IntegerField(verbose_name='الرصيد بعده')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_credits', to='tenancy.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'حركة رصيد رسائل',
                'verbose_name_plural': 'حركات رصيد الرسائل',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='credit_org_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='credit_delta_not_zero')],
            },
        ),
        migrations.CreateModel(
            name='MessageWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0, verbose_name='الرصيد')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_wallet', to='tenancy.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'محفظة رسائل',
                'verbose_name_plural': 'محافظ الرسائل',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='message_wallet_not_negative')],
            },
        ),
    ]
