# Generated by Django 5.1.6 on 2026-09-20 01:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loyalty', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المقدار')),
                ('reason', models.CharField(choices=[('earn', 'منح'), ('redeem', 'استبدال'), ('expire', 'انتهاء صلاحية'), ('reverse', 'عكس'), ('adjust', 'تسوية'), ('welcome', 'مكافأة انضمام')], max_length=20, verbose_name='السبب')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد بعده')),
                ('actor_label', models.CharField(blank=True, max_length=120, verbose_name='الفاعل')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='loyalty.membership', verbose_name='العضوية')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='loyalty.loyaltyprogram', verbose_name='البرنامج')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.ledgerentry', verbose_name='يعكس القيد')),
            ],
            options={
                'verbose_name': 'قيد',
                'verbose_name_plural': 'القيود',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الكود')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الصرف'), ('used', 'مصروفة'), ('expired', 'منتهية')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ينتهي في')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الصرف')),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redemption', to='ledger.ledgerentry', verbose_name='القيد')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.membership', verbose_name='العضوية')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.reward', verbose_name='المكافأة')),
                ('used_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions_served', to='tenancy.staffuser', verbose_name='صرفها')),
            ],
            options={
                'verbose_name': 'استبدال',
                'verbose_name_plural': 'الاستبدالات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_no', models.CharField(max_length=40, verbose_name='رقم الفاتورة')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قيمة الفاتورة')),
                ('code_used', models.CharField(blank=True, max_length=12, verbose_name='الرمز المستخدم')),
                ('status', models.CharField(choices=[('pending', 'معلّقة'), ('confirmed', 'مؤكّدة'), ('rejected', 'مرفوضة'), ('reversed', 'معكوسة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التأكيد')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.customer', verbose_name='العميل')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tenancy.staffuser', verbose_name='الكاشير')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tenancy.terminal', verbose_name='نقطة البيع')),
            ],
            options={
                'verbose_name': 'عملية',
                'verbose_name_plural': 'العمليات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.transaction', verbose_name='العملية'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='txn_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('terminal', 'invoice_no'), name='unique_invoice_per_terminal'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['membership', 'program', '-created_at'], name='entry_wallet_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reason', '-created_at'], name='entry_reason_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('delta', Decimal('0')), _negated=True), name='entry_delta_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reverses__isnull', False)), fields=('reverses',), name='entry_reversed_once'),
        ),
    ]
