# Generated by Django 5.1.6 on 2026-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="note",
            field=models.CharField(blank=True, max_length=200, verbose_name="السبب المكتوب"),
        ),
    ]
