# Generated by Django 5.1.6 on 2026-09-20 01:13

import apps.accounts.models
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة دولية، مثل \u200e+201012345678.', regex='^\\+\\d{8,19}$')], verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='الاسم الكامل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='وصول لوحة الإدارة')),
                ('is_platform_admin', models.BooleanField(default=False, verbose_name='مدير منصة')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة دولية، مثل \u200e+201012345678.', regex='^\\+\\d{8,19}$')], verbose_name='الهاتف')),
                ('full_name', models.CharField(blank=True, max_length=120, verbose_name='الاسم')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('consent_version', models.CharField(blank=True, max_length=20, verbose_name='نسخة النص')),
                ('push_subscription', models.JSONField(blank=True, null=True, verbose_name='اشتراك الإشعارات')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone'], name='customer_phone_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة دولية، مثل \u200e+201012345678.', regex='^\\+\\d{8,19}$')])),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('login', 'تسجيل الدخول'), ('delete_account', 'حذف الحساب')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'كود تحقق',
                'verbose_name_plural': 'أكواد التحقق',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'purpose', '-created_at'], name='otp_lookup_idx')],
            },
        ),
    ]
