# Generated by Django 5.1.6 on 2026-09-20 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة دولية، مثل \u200e+201012345678.', regex='^(\\+\\d{8,19}|deleted-[0-9a-f]{1,32})$')], verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة دولية، مثل \u200e+201012345678.', regex='^(\\+\\d{8,19}|deleted-[0-9a-f]{1,32})$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بصيغة دولية، مثل \u200e+201012345678.', regex='^(\\+\\d{8,19}|deleted-[0-9a-f]{1,32})$')], verbose_name='الهاتف'),
        ),
    ]
