# Generated by Django 5.1.6 on 2026-09-20 01:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('points', 'نقاط'), ('stamps', 'أختام'), ('visits', 'زيارات'), ('cashback', 'استرداد نقدي'), ('rewards', 'مكافآت'), ('gifts', 'هدايا')], max_length=20, verbose_name='النموذج')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tenancy.brand', verbose_name='العلامة')),
            ],
            options={
                'verbose_name': 'برنامج ولاء',
                'verbose_name_plural': 'برامج الولاء',
                'ordering': ('brand__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('blocked', 'محظورة')], default='active', max_length=20, verbose_name='الحالة')),
                ('tier', models.CharField(blank=True, max_length=40, verbose_name='المستوى')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.brand', verbose_name='العلامة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'العضويات',
                'ordering': ('-joined_at',),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='الرصيد')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ينتهي في')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='loyalty.loyaltyprogram', verbose_name='البرنامج')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='loyalty.membership', verbose_name='العضوية')),
            ],
            options={
                'verbose_name': 'رصيد',
                'verbose_name_plural': 'الأرصدة',
            },
        ),
        migrations.CreateModel(
            name='ProgramRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earn_rate', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='نقاط لكل جنيه · أو ختم لكل فاتورة مؤهّلة', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='معدل المنح')),
                ('min_invoice', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='أقل فاتورة مؤهّلة')),
                ('max_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='أقصى ما يُمنح للعميل الواحد في اليوم. فارغ = بلا سقف.', max_digits=12, null=True, verbose_name='السقف اليومي')),
                ('expiry_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='صلاحية الرصيد بالأشهر')),
                ('reversal_policy', models.CharField(choices=[('allow', 'مسموح للكاشير'), ('manager_only', 'المدير فقط'), ('deny', 'ممنوع')], default='manager_only', max_length=20, verbose_name='سياسة العكس')),
                ('welcome_bonus', models.PositiveIntegerField(default=0, verbose_name='مكافأة الانضمام')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='loyalty.loyaltyprogram', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'قاعدة برنامج',
                'verbose_name_plural': 'قواعد البرامج',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='التكلفة بالوحدات')),
                ('cost_unit', models.CharField(choices=[('points', 'نقاط'), ('stamps', 'أختام')], default='points', max_length=20, verbose_name='الوحدة')),
                ('merchant_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='تكلفتها على التاجر')),
                ('stock', models.IntegerField(blank=True, help_text='فارغ = بلا حد', null=True, verbose_name='المخزون')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='loyalty.loyaltyprogram', verbose_name='البرنامج')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
                'ordering': ('cost_amount',),
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('customer', 'brand'), name='unique_membership_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.UniqueConstraint(fields=('membership', 'program'), name='unique_balance_per_program'),
        ),
        migrations.AddConstraint(
            model_name='balance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0'))), name='balance_never_negative'),
        ),
    ]
