# Generated by Django 5.1.6 on 2026-09-20 01:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(db_index=True, max_length=40, verbose_name='رمز القاعدة')),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='low', max_length=10, verbose_name='الخطورة')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('status', models.CharField(choices=[('open', 'بانتظار المراجعة'), ('accepted', 'مقبولة — العملية سليمة'), ('rejected', 'مرفوضة — عُكست العملية')], db_index=True, default='open', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fraud_reviews', to='tenancy.staffuser', verbose_name='راجعها')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_signals', to='ledger.transaction', verbose_name='العملية')),
            ],
            options={
                'verbose_name': 'إشارة شذوذ',
                'verbose_name_plural': 'إشارات الشذوذ',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('transaction', 'rule_code'), name='unique_signal_per_rule')],
            },
        ),
    ]
